###
// Get all blocks
GET http://localhost:5700/api/v2/block

###
// Get all blocks
GET http://localhost:5700/api/v2/blockchain



###
// Create a new blockchain
POST http://localhost:5700/api/v2/blockchain/init
Content-Type: application/json

{
  "name": "Virtue",
  "consensusRules": {
    "consensusAlgorithm": "Proof of Stake, Proof of History",
    "maxValidators": 20,
    "proposalThreshold": 75,
    "upgradeProtocol": "BFT",
    "signingAlgorithm": "ECDSA",
    "curve": "curve25519"
  }
}

###
// Create Native Coin
POST http://localhost:5700/api/v2/vrt



###
// Create a new account
POST http://localhost:5700/api/v2/account/create-account

###
// Create a new wallet
POST http://localhost:5700/api/v2/account/
Content-Type: application/json

{
  "password": "2233"
}


###
// Login
POST http://localhost:5700/api/v2/account/login
Content-Type: application/json

{
  "password": "2233"
}


###
// Create Token
POST http://localhost:5700/api/v2/token
Content-Type: application/json

{
  "name": "Boxing Nation Virtron",
  "uri": "BNV.COM",
  "symbol": "BNV",
  "mintAuthority": "ZmbgmWKToM3VZBRDjfKL6ptAsPqhpGGSNtEgVjojLSdd",
  "freezeAuthority": "ZmbgmWKToM3VZBRDjfKL6ptAsPqhpGGSNtEgVjojLSdd"
}

###
// Create Management Contract
POST http://localhost:5700/api/v2/managerContract
Content-Type: application/json

{
  "fighter": "64f134d8123456f6f987ab00", 
  "manager": "64f235a46789a4d112345ff9", 
  "term": {
    "totalFights": 6
  },
  "compensation": {
    "perFightMin": 1000, 
    "bonuses": [
      {
        "title": "KO Bonus",
        "amount": 1000
      }
    ]
  },
  "obligations": [
    "Must fight at least once every two weeks",
    "Complete 1 mandatory training session before each fight"
  ],
  "perks": [
    "Access to private training facility",
    "Sponsorship opportunities"
  ],
  "terminationClauses": [
    "Manager may terminate if fighter misses two scheduled fights",
    "Fighter can terminate if compensation is delayed"
  ],
  "fighterSignature": null, 
  "managerSignature": "55DTMPqsNxoqXmipToA75RXwQWKoASzys8doZM56ERSMrRHmUX9oUqbzidSUryAwdpYCgA31pRmQFPDYU5Lh8pBs"
}



