###
// Create a new blockchain
POST http://localhost:5700/api/v2/blockchain/create
Content-Type: application/json

{
  "name": "juroz",
  "consensusRules": {
    "consensusAlgorithm": "Proof of Stake, Proof of History",
    "maxValidators": 20,
    "proposalThreshold": 75,
    "upgradeProtocol": "BFT",
    "signingAlgorithm": "ECDSA",
    "curve": "curve25519"
  }
}

###
// Get all blocks
GET http://localhost:5700/api/v2/block


###
// Create a new account
POST http://localhost:5700/api/v2/account
Content-Type: application/json

{
  "password": "8999"
}

###
// Login
POST http://localhost:5700/api/v2/account/login
Content-Type: application/json

{
  "password": "8999"
}